### ISSUE TITLE
¿Cómo obtener el código necesario para la votación?

### ISSUE THREAD

**Issue by davarresc** [EGCPractica/agora-gui-booth#1]
Al estar el sistema en pruebas no envía ni correos ni sms, entonces al enviar el código a un usuario no encuentro la manera de obtener el código para aceptar la votación.

**Comment by aamjX** [comment]
Solucionado. El procedimiento a seguir es el siguiente:

Una vez realizada la votación, para poder acceder a los códigos y enlaces necesarios tenemos que ir a la máquina de agora en la que previamente deberíamos habernos conectado por SSH. Una vez allí introducimos en siguiente comando: "sudo supervisorctl tail -f authapi_celery"

Nos aparecerá el log de authapi_celery, donde aparecerá el correo que se debería haber enviado y el cual contiene los códigos y enlaces necesarios.
