### ISSUE TITLE
Error de Usuarios

### ISSUE THREAD

**Issue by Armandoccdl** [EGCPractica/agora-gui-booth#3]
El ultimo commit de agora-gui-booth (Skip links) fue realizado por Armando Conejero Calvo de León (Armandoccdl) y no por Antonio Espinosa (Espinosa13).
Este problema se produjo cuando la por un fallo de la maquina de Armando, este tuvo que seguir trabajando desde la maquina de Antonio y a la hora de hacer el commit no se modifico la configuración de git de la maquina de Antonio.

Disculpen las molestias.

Saludos.

**Comment by Espinosa13** [comment]
Verificó que se realizó lo dicho en esta issue es cierto.
